language: node_js
sudo: required
node_js: 
  - 7.9.0

cache:
  directories:
    - node_modules

branches:
  only:
    - hexo 

before_install:
  - npm install -g hexo-cli

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

before_script:
 # - npm install -g gulp
 - echo ${GH_REPO}
 - echo ${CODING_REPO}
 - echo ${Baidu_Url_Submit_Token}

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "xiongxunxiang"
  - git config user.email "xiongxunxiang_it@163.com"
  - hexo deploy
# E: Build LifeCycle

